name: 'financial_sentiment'
version: '1.0.0'
config-version: 2

profile: 'financial_sentiment'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  financial_sentiment:
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: ephemeral

vars:
  # Variables del proyecto
  news_table: "{{ ref('stg_news') }}"
  stock_table: "{{ ref('stg_stock_prices') }}"
  sentiment_table: "{{ ref('stg_sentiment_scores') }}"

seeds:
  financial_sentiment:
    +column_types:
      id: integer
      created_at: timestamp 