"""Initial migration - create all tables

Revision ID: 061e66819f74
Revises: 
Create Date: 2025-07-06 01:11:09.436030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061e66819f74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear tabla financial_sentiment_correlation
    op.create_table('financial_sentiment_correlation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hour', sa.DateTime(), nullable=False),
        sa.Column('symbol', sa.String(length=10), nullable=True),
        sa.Column('avg_sentiment_score', sa.Float(), nullable=True),
        sa.Column('avg_sentiment_subjectivity', sa.Float(), nullable=True),
        sa.Column('avg_close_price', sa.Float(), nullable=True),
        sa.Column('max_high_price', sa.Float(), nullable=True),
        sa.Column('min_low_price', sa.Float(), nullable=True),
        sa.Column('total_volume', sa.Integer(), nullable=True),
        sa.Column('price_points', sa.Integer(), nullable=True),
        sa.Column('news_count', sa.Integer(), nullable=True),
        sa.Column('sentiment_category', sa.String(length=20), nullable=True),
        sa.Column('price_change_percent', sa.Float(), nullable=True),
        sa.Column('sentiment_change', sa.Float(), nullable=True),
        sa.Column('correlation_coefficient', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_sentiment_correlation_hour'), 'financial_sentiment_correlation', ['hour'], unique=False)
    op.create_index(op.f('ix_financial_sentiment_correlation_id'), 'financial_sentiment_correlation', ['id'], unique=False)
    op.create_index(op.f('ix_financial_sentiment_correlation_symbol'), 'financial_sentiment_correlation', ['symbol'], unique=False)
    
    # Crear tabla news_with_sentiment
    op.create_table('news_with_sentiment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('source_name', sa.String(length=100), nullable=True),
        sa.Column('sentiment_score', sa.Float(), nullable=True),
        sa.Column('sentiment_subjectivity', sa.Float(), nullable=True),
        sa.Column('symbol', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_with_sentiment_id'), 'news_with_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_news_with_sentiment_published_at'), 'news_with_sentiment', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_with_sentiment_symbol'), 'news_with_sentiment', ['symbol'], unique=False)
    
    # Crear tabla stock_prices
    op.create_table('stock_prices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=10), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('open_price', sa.Float(), nullable=True),
        sa.Column('high_price', sa.Float(), nullable=True),
        sa.Column('low_price', sa.Float(), nullable=True),
        sa.Column('close_price', sa.Float(), nullable=False),
        sa.Column('volume', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prices_id'), 'stock_prices', ['id'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_prices_timestamp'), 'stock_prices', ['timestamp'], unique=False)
    
    # Crear tabla users
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_prices_timestamp'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_id'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_news_with_sentiment_symbol'), table_name='news_with_sentiment')
    op.drop_index(op.f('ix_news_with_sentiment_published_at'), table_name='news_with_sentiment')
    op.drop_index(op.f('ix_news_with_sentiment_id'), table_name='news_with_sentiment')
    op.drop_table('news_with_sentiment')
    op.drop_index(op.f('ix_financial_sentiment_correlation_symbol'), table_name='financial_sentiment_correlation')
    op.drop_index(op.f('ix_financial_sentiment_correlation_id'), table_name='financial_sentiment_correlation')
    op.drop_index(op.f('ix_financial_sentiment_correlation_hour'), table_name='financial_sentiment_correlation')
    op.drop_table('financial_sentiment_correlation')
    # ### end Alembic commands ###
